name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      - name: Authenticate with Salesforce (JWT)
        run: |
          echo "Storing private key..."
          echo "${{ secrets.SF_SANDBOX_JWT_KEY }}"  | base64 --decode > server.key
          ls -la server.key  # Check if key is created
          echo "Authenticating with Salesforce..."
          sfdx auth:jwt:grant \
            --client-id "${{ secrets.SF_SANDBOX_CLIENT_ID }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SF_SANDBOX_USERNAME }}" \
            --instance-url "${{ secrets.SF_SANDBOX_URL }}" \
            --set-default-dev-hub \
            --set-default

      - name: Verify Authentication
        run: sfdx force:org:list --all

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app/main/default/classes/CaseImageController.cls -u "${{ secrets.SF_SANDBOX_USERNAME }}"
