name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify SFDX Project
        run: |
          ls -la
          if [ ! -f "sfdx-project.json" ]; then
            echo "Error: Not inside an SFDX project!"
            exit 1
          fi

      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      - name: Authenticate with JWT
        run: |
          echo "$SF_SANDBOX_JWT_KEY" > server.key
          sfdx auth jwt grant --client-id "$SF_SANDBOX_CLIENT_ID" --jwt-key-file server.key --username "$SF_SANDBOX_USERNAME" --instance-url "$SF_SANDBOX_URL"

      - name: Deploy to Salesforce
        run: |
          cd $GITHUB_WORKSPACE
          sfdx force:source:deploy -p force-app -u "$SF_SANDBOX_USERNAME"
